services:
  - type: web
    name: lenny-raffle-lookup
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
    autoDeploy: true
